# Generated by Django 5.0.2 on 2024-05-08 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprovider',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
