# Generated by Django 5.0.2 on 2024-03-02 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requests_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='user',
            new_name='customer',
        ),
    ]
